// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module AsyncQueueSink_23(
  input        clock,
               reset,
  output       io_deq_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  output [8:0] io_deq_bits_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  output       io_deq_bits_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_0_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_0_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_1_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_1_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_2_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_2_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_3_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_3_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_4_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_4_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_5_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_5_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_6_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_6_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_7_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_7_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_8_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_8_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_9_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_9_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_10_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_10_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_11_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_11_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_12_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_12_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_13_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_13_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_14_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_14_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_15_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_15_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_16_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_16_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_17_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_17_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_18_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_18_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_19_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_19_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_20_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_20_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_21_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_21_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_22_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_22_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_23_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_23_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_24_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_24_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_25_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_25_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_26_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_26_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_27_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_27_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_28_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_28_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_29_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_29_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_30_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_30_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_31_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_31_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_32_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_32_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_33_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_33_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_34_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_34_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_35_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_35_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_36_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_36_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_37_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_37_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_38_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_38_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_39_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_39_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_40_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_40_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_41_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_41_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_42_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_42_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_43_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_43_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_44_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_44_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_45_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_45_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_46_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_46_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_47_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_47_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_48_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_48_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_49_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_49_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_50_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_50_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_51_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_51_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_52_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_52_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_53_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_53_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_54_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_54_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_55_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_55_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_56_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_56_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_57_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_57_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_58_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_58_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_59_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_59_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_60_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_60_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_61_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_61_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_62_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_62_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_63_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_63_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_64_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_64_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_65_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_65_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_66_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_66_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_67_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_67_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_68_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_68_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_69_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_69_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_70_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_70_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_71_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_71_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_72_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_72_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_73_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_73_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_74_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_74_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_75_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_75_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_76_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_76_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_77_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_77_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_78_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_78_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_79_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_79_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_80_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_80_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_81_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_81_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_82_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_82_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_83_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_83_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_84_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_84_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_85_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_85_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_86_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_86_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_87_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_87_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_88_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_88_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_89_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_89_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_90_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_90_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_91_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_91_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_92_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_92_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_93_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_93_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_94_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_94_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_95_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_95_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_96_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_96_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_97_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_97_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_98_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_98_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_99_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_99_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_100_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_100_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_101_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_101_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_102_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_102_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_103_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_103_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_104_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_104_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_105_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_105_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_106_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_106_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_107_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_107_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_108_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_108_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_109_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_109_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_110_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_110_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_111_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_111_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_112_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_112_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_113_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_113_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_114_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_114_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_115_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_115_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_116_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_116_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_117_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_117_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_118_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_118_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_119_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_119_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_120_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_120_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_121_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_121_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_122_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_122_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_123_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_123_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_124_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_124_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_125_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_125_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_126_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_126_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_127_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_127_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_128_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_128_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_129_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_129_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_130_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_130_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_131_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_131_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_132_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_132_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_133_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_133_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_134_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_134_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_135_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_135_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_136_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_136_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_137_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_137_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_138_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_138_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_139_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_139_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_140_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_140_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_141_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_141_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_142_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_142_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_143_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_143_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_144_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_144_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_145_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_145_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_146_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_146_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_147_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_147_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_148_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_148_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_149_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_149_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_150_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_150_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_151_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_151_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_152_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_152_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_153_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_153_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_154_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_154_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_155_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_155_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_156_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_156_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_157_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_157_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_158_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_158_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_159_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_159_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_160_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_160_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_161_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_161_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_162_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_162_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_163_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_163_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_164_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_164_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_165_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_165_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_166_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_166_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_167_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_167_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_168_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_168_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_169_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_169_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_170_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_170_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_171_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_171_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_172_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_172_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_173_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_173_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_174_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_174_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_175_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_175_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_176_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_176_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_177_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_177_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_178_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_178_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_179_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_179_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_180_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_180_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_181_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_181_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_182_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_182_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_183_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_183_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_184_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_184_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_185_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_185_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_186_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_186_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_187_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_187_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_188_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_188_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_189_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_189_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_190_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_190_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_191_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_191_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_192_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_192_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_193_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_193_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_194_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_194_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_195_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_195_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_196_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_196_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_197_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_197_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_198_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_198_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_199_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_199_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_200_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_200_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_201_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_201_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_202_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_202_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_203_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_203_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_204_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_204_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_205_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_205_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_206_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_206_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_207_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_207_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_208_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_208_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_209_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_209_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_210_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_210_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_211_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_211_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_212_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_212_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_213_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_213_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_214_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_214_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_215_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_215_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_216_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_216_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_217_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_217_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_218_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_218_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_219_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_219_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_220_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_220_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_221_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_221_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_222_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_222_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_223_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_223_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_224_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_224_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_225_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_225_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_226_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_226_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_227_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_227_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_228_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_228_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_229_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_229_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_230_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_230_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_231_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_231_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_232_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_232_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_233_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_233_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_234_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_234_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_235_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_235_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_236_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_236_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_237_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_237_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_238_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_238_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_239_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_239_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_240_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_240_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_241_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_241_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_242_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_242_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_243_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_243_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_244_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_244_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_245_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_245_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_246_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_246_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_247_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_247_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_248_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_248_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_249_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_249_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_250_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_250_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_251_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_251_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_252_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_252_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_253_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_253_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_254_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_254_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_mem_255_gain,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_mem_255_reset,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  output [8:0] io_async_ridx,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input  [8:0] io_async_widx,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  output       io_async_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  input        io_async_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
               io_async_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
  output       io_async_safe_sink_reset_n	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:135:14]
);

  wire              io_deq_valid_0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:162:29]
  wire              _source_valid_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:172:31]
  wire              _source_extend_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:171:31]
  wire              _sink_valid_0_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:168:33]
  wire [9:0]        _io_deq_bits_deq_bits_reg_io_q;	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:207:25]
  wire [8:0]        _widx_widx_gray_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  reg  [8:0]        ridx_ridx_bin;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
  wire [8:0]        _ridx_incremented_T = ridx_ridx_bin + {8'h0, io_deq_valid_0};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:43, :162:29]
  wire [8:0]        ridx_incremented = _source_valid_io_out ? _ridx_incremented_T : 9'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:{23,43}, :172:31]
  wire [7:0]        _index_T = ridx_incremented[7:0] ^ ridx_incremented[8:1];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :54:{17,32}]
  wire [8:0]        ridx = {ridx_incremented[8], _index_T};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :54:17]
  wire              valid = _source_valid_io_out & ridx != _widx_widx_gray_io_q;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:54:17, :146:{28,36}, :172:31, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire [7:0]        index = _index_T ^ {ridx_incremented[8], 7'h0};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :54:17, :152:{55,75}]
  wire [255:0][8:0] _GEN =
    {{io_async_mem_255_gain},
     {io_async_mem_254_gain},
     {io_async_mem_253_gain},
     {io_async_mem_252_gain},
     {io_async_mem_251_gain},
     {io_async_mem_250_gain},
     {io_async_mem_249_gain},
     {io_async_mem_248_gain},
     {io_async_mem_247_gain},
     {io_async_mem_246_gain},
     {io_async_mem_245_gain},
     {io_async_mem_244_gain},
     {io_async_mem_243_gain},
     {io_async_mem_242_gain},
     {io_async_mem_241_gain},
     {io_async_mem_240_gain},
     {io_async_mem_239_gain},
     {io_async_mem_238_gain},
     {io_async_mem_237_gain},
     {io_async_mem_236_gain},
     {io_async_mem_235_gain},
     {io_async_mem_234_gain},
     {io_async_mem_233_gain},
     {io_async_mem_232_gain},
     {io_async_mem_231_gain},
     {io_async_mem_230_gain},
     {io_async_mem_229_gain},
     {io_async_mem_228_gain},
     {io_async_mem_227_gain},
     {io_async_mem_226_gain},
     {io_async_mem_225_gain},
     {io_async_mem_224_gain},
     {io_async_mem_223_gain},
     {io_async_mem_222_gain},
     {io_async_mem_221_gain},
     {io_async_mem_220_gain},
     {io_async_mem_219_gain},
     {io_async_mem_218_gain},
     {io_async_mem_217_gain},
     {io_async_mem_216_gain},
     {io_async_mem_215_gain},
     {io_async_mem_214_gain},
     {io_async_mem_213_gain},
     {io_async_mem_212_gain},
     {io_async_mem_211_gain},
     {io_async_mem_210_gain},
     {io_async_mem_209_gain},
     {io_async_mem_208_gain},
     {io_async_mem_207_gain},
     {io_async_mem_206_gain},
     {io_async_mem_205_gain},
     {io_async_mem_204_gain},
     {io_async_mem_203_gain},
     {io_async_mem_202_gain},
     {io_async_mem_201_gain},
     {io_async_mem_200_gain},
     {io_async_mem_199_gain},
     {io_async_mem_198_gain},
     {io_async_mem_197_gain},
     {io_async_mem_196_gain},
     {io_async_mem_195_gain},
     {io_async_mem_194_gain},
     {io_async_mem_193_gain},
     {io_async_mem_192_gain},
     {io_async_mem_191_gain},
     {io_async_mem_190_gain},
     {io_async_mem_189_gain},
     {io_async_mem_188_gain},
     {io_async_mem_187_gain},
     {io_async_mem_186_gain},
     {io_async_mem_185_gain},
     {io_async_mem_184_gain},
     {io_async_mem_183_gain},
     {io_async_mem_182_gain},
     {io_async_mem_181_gain},
     {io_async_mem_180_gain},
     {io_async_mem_179_gain},
     {io_async_mem_178_gain},
     {io_async_mem_177_gain},
     {io_async_mem_176_gain},
     {io_async_mem_175_gain},
     {io_async_mem_174_gain},
     {io_async_mem_173_gain},
     {io_async_mem_172_gain},
     {io_async_mem_171_gain},
     {io_async_mem_170_gain},
     {io_async_mem_169_gain},
     {io_async_mem_168_gain},
     {io_async_mem_167_gain},
     {io_async_mem_166_gain},
     {io_async_mem_165_gain},
     {io_async_mem_164_gain},
     {io_async_mem_163_gain},
     {io_async_mem_162_gain},
     {io_async_mem_161_gain},
     {io_async_mem_160_gain},
     {io_async_mem_159_gain},
     {io_async_mem_158_gain},
     {io_async_mem_157_gain},
     {io_async_mem_156_gain},
     {io_async_mem_155_gain},
     {io_async_mem_154_gain},
     {io_async_mem_153_gain},
     {io_async_mem_152_gain},
     {io_async_mem_151_gain},
     {io_async_mem_150_gain},
     {io_async_mem_149_gain},
     {io_async_mem_148_gain},
     {io_async_mem_147_gain},
     {io_async_mem_146_gain},
     {io_async_mem_145_gain},
     {io_async_mem_144_gain},
     {io_async_mem_143_gain},
     {io_async_mem_142_gain},
     {io_async_mem_141_gain},
     {io_async_mem_140_gain},
     {io_async_mem_139_gain},
     {io_async_mem_138_gain},
     {io_async_mem_137_gain},
     {io_async_mem_136_gain},
     {io_async_mem_135_gain},
     {io_async_mem_134_gain},
     {io_async_mem_133_gain},
     {io_async_mem_132_gain},
     {io_async_mem_131_gain},
     {io_async_mem_130_gain},
     {io_async_mem_129_gain},
     {io_async_mem_128_gain},
     {io_async_mem_127_gain},
     {io_async_mem_126_gain},
     {io_async_mem_125_gain},
     {io_async_mem_124_gain},
     {io_async_mem_123_gain},
     {io_async_mem_122_gain},
     {io_async_mem_121_gain},
     {io_async_mem_120_gain},
     {io_async_mem_119_gain},
     {io_async_mem_118_gain},
     {io_async_mem_117_gain},
     {io_async_mem_116_gain},
     {io_async_mem_115_gain},
     {io_async_mem_114_gain},
     {io_async_mem_113_gain},
     {io_async_mem_112_gain},
     {io_async_mem_111_gain},
     {io_async_mem_110_gain},
     {io_async_mem_109_gain},
     {io_async_mem_108_gain},
     {io_async_mem_107_gain},
     {io_async_mem_106_gain},
     {io_async_mem_105_gain},
     {io_async_mem_104_gain},
     {io_async_mem_103_gain},
     {io_async_mem_102_gain},
     {io_async_mem_101_gain},
     {io_async_mem_100_gain},
     {io_async_mem_99_gain},
     {io_async_mem_98_gain},
     {io_async_mem_97_gain},
     {io_async_mem_96_gain},
     {io_async_mem_95_gain},
     {io_async_mem_94_gain},
     {io_async_mem_93_gain},
     {io_async_mem_92_gain},
     {io_async_mem_91_gain},
     {io_async_mem_90_gain},
     {io_async_mem_89_gain},
     {io_async_mem_88_gain},
     {io_async_mem_87_gain},
     {io_async_mem_86_gain},
     {io_async_mem_85_gain},
     {io_async_mem_84_gain},
     {io_async_mem_83_gain},
     {io_async_mem_82_gain},
     {io_async_mem_81_gain},
     {io_async_mem_80_gain},
     {io_async_mem_79_gain},
     {io_async_mem_78_gain},
     {io_async_mem_77_gain},
     {io_async_mem_76_gain},
     {io_async_mem_75_gain},
     {io_async_mem_74_gain},
     {io_async_mem_73_gain},
     {io_async_mem_72_gain},
     {io_async_mem_71_gain},
     {io_async_mem_70_gain},
     {io_async_mem_69_gain},
     {io_async_mem_68_gain},
     {io_async_mem_67_gain},
     {io_async_mem_66_gain},
     {io_async_mem_65_gain},
     {io_async_mem_64_gain},
     {io_async_mem_63_gain},
     {io_async_mem_62_gain},
     {io_async_mem_61_gain},
     {io_async_mem_60_gain},
     {io_async_mem_59_gain},
     {io_async_mem_58_gain},
     {io_async_mem_57_gain},
     {io_async_mem_56_gain},
     {io_async_mem_55_gain},
     {io_async_mem_54_gain},
     {io_async_mem_53_gain},
     {io_async_mem_52_gain},
     {io_async_mem_51_gain},
     {io_async_mem_50_gain},
     {io_async_mem_49_gain},
     {io_async_mem_48_gain},
     {io_async_mem_47_gain},
     {io_async_mem_46_gain},
     {io_async_mem_45_gain},
     {io_async_mem_44_gain},
     {io_async_mem_43_gain},
     {io_async_mem_42_gain},
     {io_async_mem_41_gain},
     {io_async_mem_40_gain},
     {io_async_mem_39_gain},
     {io_async_mem_38_gain},
     {io_async_mem_37_gain},
     {io_async_mem_36_gain},
     {io_async_mem_35_gain},
     {io_async_mem_34_gain},
     {io_async_mem_33_gain},
     {io_async_mem_32_gain},
     {io_async_mem_31_gain},
     {io_async_mem_30_gain},
     {io_async_mem_29_gain},
     {io_async_mem_28_gain},
     {io_async_mem_27_gain},
     {io_async_mem_26_gain},
     {io_async_mem_25_gain},
     {io_async_mem_24_gain},
     {io_async_mem_23_gain},
     {io_async_mem_22_gain},
     {io_async_mem_21_gain},
     {io_async_mem_20_gain},
     {io_async_mem_19_gain},
     {io_async_mem_18_gain},
     {io_async_mem_17_gain},
     {io_async_mem_16_gain},
     {io_async_mem_15_gain},
     {io_async_mem_14_gain},
     {io_async_mem_13_gain},
     {io_async_mem_12_gain},
     {io_async_mem_11_gain},
     {io_async_mem_10_gain},
     {io_async_mem_9_gain},
     {io_async_mem_8_gain},
     {io_async_mem_7_gain},
     {io_async_mem_6_gain},
     {io_async_mem_5_gain},
     {io_async_mem_4_gain},
     {io_async_mem_3_gain},
     {io_async_mem_2_gain},
     {io_async_mem_1_gain},
     {io_async_mem_0_gain}};	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:209:24]
  wire [255:0]      _GEN_0 =
    {{io_async_mem_255_reset},
     {io_async_mem_254_reset},
     {io_async_mem_253_reset},
     {io_async_mem_252_reset},
     {io_async_mem_251_reset},
     {io_async_mem_250_reset},
     {io_async_mem_249_reset},
     {io_async_mem_248_reset},
     {io_async_mem_247_reset},
     {io_async_mem_246_reset},
     {io_async_mem_245_reset},
     {io_async_mem_244_reset},
     {io_async_mem_243_reset},
     {io_async_mem_242_reset},
     {io_async_mem_241_reset},
     {io_async_mem_240_reset},
     {io_async_mem_239_reset},
     {io_async_mem_238_reset},
     {io_async_mem_237_reset},
     {io_async_mem_236_reset},
     {io_async_mem_235_reset},
     {io_async_mem_234_reset},
     {io_async_mem_233_reset},
     {io_async_mem_232_reset},
     {io_async_mem_231_reset},
     {io_async_mem_230_reset},
     {io_async_mem_229_reset},
     {io_async_mem_228_reset},
     {io_async_mem_227_reset},
     {io_async_mem_226_reset},
     {io_async_mem_225_reset},
     {io_async_mem_224_reset},
     {io_async_mem_223_reset},
     {io_async_mem_222_reset},
     {io_async_mem_221_reset},
     {io_async_mem_220_reset},
     {io_async_mem_219_reset},
     {io_async_mem_218_reset},
     {io_async_mem_217_reset},
     {io_async_mem_216_reset},
     {io_async_mem_215_reset},
     {io_async_mem_214_reset},
     {io_async_mem_213_reset},
     {io_async_mem_212_reset},
     {io_async_mem_211_reset},
     {io_async_mem_210_reset},
     {io_async_mem_209_reset},
     {io_async_mem_208_reset},
     {io_async_mem_207_reset},
     {io_async_mem_206_reset},
     {io_async_mem_205_reset},
     {io_async_mem_204_reset},
     {io_async_mem_203_reset},
     {io_async_mem_202_reset},
     {io_async_mem_201_reset},
     {io_async_mem_200_reset},
     {io_async_mem_199_reset},
     {io_async_mem_198_reset},
     {io_async_mem_197_reset},
     {io_async_mem_196_reset},
     {io_async_mem_195_reset},
     {io_async_mem_194_reset},
     {io_async_mem_193_reset},
     {io_async_mem_192_reset},
     {io_async_mem_191_reset},
     {io_async_mem_190_reset},
     {io_async_mem_189_reset},
     {io_async_mem_188_reset},
     {io_async_mem_187_reset},
     {io_async_mem_186_reset},
     {io_async_mem_185_reset},
     {io_async_mem_184_reset},
     {io_async_mem_183_reset},
     {io_async_mem_182_reset},
     {io_async_mem_181_reset},
     {io_async_mem_180_reset},
     {io_async_mem_179_reset},
     {io_async_mem_178_reset},
     {io_async_mem_177_reset},
     {io_async_mem_176_reset},
     {io_async_mem_175_reset},
     {io_async_mem_174_reset},
     {io_async_mem_173_reset},
     {io_async_mem_172_reset},
     {io_async_mem_171_reset},
     {io_async_mem_170_reset},
     {io_async_mem_169_reset},
     {io_async_mem_168_reset},
     {io_async_mem_167_reset},
     {io_async_mem_166_reset},
     {io_async_mem_165_reset},
     {io_async_mem_164_reset},
     {io_async_mem_163_reset},
     {io_async_mem_162_reset},
     {io_async_mem_161_reset},
     {io_async_mem_160_reset},
     {io_async_mem_159_reset},
     {io_async_mem_158_reset},
     {io_async_mem_157_reset},
     {io_async_mem_156_reset},
     {io_async_mem_155_reset},
     {io_async_mem_154_reset},
     {io_async_mem_153_reset},
     {io_async_mem_152_reset},
     {io_async_mem_151_reset},
     {io_async_mem_150_reset},
     {io_async_mem_149_reset},
     {io_async_mem_148_reset},
     {io_async_mem_147_reset},
     {io_async_mem_146_reset},
     {io_async_mem_145_reset},
     {io_async_mem_144_reset},
     {io_async_mem_143_reset},
     {io_async_mem_142_reset},
     {io_async_mem_141_reset},
     {io_async_mem_140_reset},
     {io_async_mem_139_reset},
     {io_async_mem_138_reset},
     {io_async_mem_137_reset},
     {io_async_mem_136_reset},
     {io_async_mem_135_reset},
     {io_async_mem_134_reset},
     {io_async_mem_133_reset},
     {io_async_mem_132_reset},
     {io_async_mem_131_reset},
     {io_async_mem_130_reset},
     {io_async_mem_129_reset},
     {io_async_mem_128_reset},
     {io_async_mem_127_reset},
     {io_async_mem_126_reset},
     {io_async_mem_125_reset},
     {io_async_mem_124_reset},
     {io_async_mem_123_reset},
     {io_async_mem_122_reset},
     {io_async_mem_121_reset},
     {io_async_mem_120_reset},
     {io_async_mem_119_reset},
     {io_async_mem_118_reset},
     {io_async_mem_117_reset},
     {io_async_mem_116_reset},
     {io_async_mem_115_reset},
     {io_async_mem_114_reset},
     {io_async_mem_113_reset},
     {io_async_mem_112_reset},
     {io_async_mem_111_reset},
     {io_async_mem_110_reset},
     {io_async_mem_109_reset},
     {io_async_mem_108_reset},
     {io_async_mem_107_reset},
     {io_async_mem_106_reset},
     {io_async_mem_105_reset},
     {io_async_mem_104_reset},
     {io_async_mem_103_reset},
     {io_async_mem_102_reset},
     {io_async_mem_101_reset},
     {io_async_mem_100_reset},
     {io_async_mem_99_reset},
     {io_async_mem_98_reset},
     {io_async_mem_97_reset},
     {io_async_mem_96_reset},
     {io_async_mem_95_reset},
     {io_async_mem_94_reset},
     {io_async_mem_93_reset},
     {io_async_mem_92_reset},
     {io_async_mem_91_reset},
     {io_async_mem_90_reset},
     {io_async_mem_89_reset},
     {io_async_mem_88_reset},
     {io_async_mem_87_reset},
     {io_async_mem_86_reset},
     {io_async_mem_85_reset},
     {io_async_mem_84_reset},
     {io_async_mem_83_reset},
     {io_async_mem_82_reset},
     {io_async_mem_81_reset},
     {io_async_mem_80_reset},
     {io_async_mem_79_reset},
     {io_async_mem_78_reset},
     {io_async_mem_77_reset},
     {io_async_mem_76_reset},
     {io_async_mem_75_reset},
     {io_async_mem_74_reset},
     {io_async_mem_73_reset},
     {io_async_mem_72_reset},
     {io_async_mem_71_reset},
     {io_async_mem_70_reset},
     {io_async_mem_69_reset},
     {io_async_mem_68_reset},
     {io_async_mem_67_reset},
     {io_async_mem_66_reset},
     {io_async_mem_65_reset},
     {io_async_mem_64_reset},
     {io_async_mem_63_reset},
     {io_async_mem_62_reset},
     {io_async_mem_61_reset},
     {io_async_mem_60_reset},
     {io_async_mem_59_reset},
     {io_async_mem_58_reset},
     {io_async_mem_57_reset},
     {io_async_mem_56_reset},
     {io_async_mem_55_reset},
     {io_async_mem_54_reset},
     {io_async_mem_53_reset},
     {io_async_mem_52_reset},
     {io_async_mem_51_reset},
     {io_async_mem_50_reset},
     {io_async_mem_49_reset},
     {io_async_mem_48_reset},
     {io_async_mem_47_reset},
     {io_async_mem_46_reset},
     {io_async_mem_45_reset},
     {io_async_mem_44_reset},
     {io_async_mem_43_reset},
     {io_async_mem_42_reset},
     {io_async_mem_41_reset},
     {io_async_mem_40_reset},
     {io_async_mem_39_reset},
     {io_async_mem_38_reset},
     {io_async_mem_37_reset},
     {io_async_mem_36_reset},
     {io_async_mem_35_reset},
     {io_async_mem_34_reset},
     {io_async_mem_33_reset},
     {io_async_mem_32_reset},
     {io_async_mem_31_reset},
     {io_async_mem_30_reset},
     {io_async_mem_29_reset},
     {io_async_mem_28_reset},
     {io_async_mem_27_reset},
     {io_async_mem_26_reset},
     {io_async_mem_25_reset},
     {io_async_mem_24_reset},
     {io_async_mem_23_reset},
     {io_async_mem_22_reset},
     {io_async_mem_21_reset},
     {io_async_mem_20_reset},
     {io_async_mem_19_reset},
     {io_async_mem_18_reset},
     {io_async_mem_17_reset},
     {io_async_mem_16_reset},
     {io_async_mem_15_reset},
     {io_async_mem_14_reset},
     {io_async_mem_13_reset},
     {io_async_mem_12_reset},
     {io_async_mem_11_reset},
     {io_async_mem_10_reset},
     {io_async_mem_9_reset},
     {io_async_mem_8_reset},
     {io_async_mem_7_reset},
     {io_async_mem_6_reset},
     {io_async_mem_5_reset},
     {io_async_mem_4_reset},
     {io_async_mem_3_reset},
     {io_async_mem_2_reset},
     {io_async_mem_1_reset},
     {io_async_mem_0_reset}};	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:209:24]
  reg               valid_reg;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:161:56]
  assign io_deq_valid_0 = valid_reg & _source_valid_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:161:56, :162:29, :172:31]
  reg  [8:0]        ridx_gray;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:164:55]
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      ridx_ridx_bin <= 9'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:23]
      valid_reg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:161:56]
      ridx_gray <= 9'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :164:55]
    end
    else begin
      if (_source_valid_io_out)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:172:31]
        ridx_ridx_bin <= _ridx_incremented_T;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:43]
      else	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:172:31]
        ridx_ridx_bin <= 9'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:23]
      valid_reg <= valid;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:146:28, :161:56]
      ridx_gray <= ridx;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:54:17, :164:55]
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        ridx_ridx_bin = _RANDOM[/*Zero width*/ 1'b0][8:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
        valid_reg = _RANDOM[/*Zero width*/ 1'b0][9];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :161:56]
        ridx_gray = _RANDOM[/*Zero width*/ 1'b0][18:10];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :164:55]
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        ridx_ridx_bin = 9'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:23]
        valid_reg = 1'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:161:56]
        ridx_gray = 9'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :164:55]
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AsyncResetSynchronizerShiftReg_w9_d3_i0 widx_widx_gray (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .reset (reset),
    .io_d  (io_async_widx),
    .io_q  (_widx_widx_gray_io_q)
  );
  ClockCrossingReg_w10 io_deq_bits_deq_bits_reg (	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:207:25]
    .clock (clock),
    .io_d  ({_GEN[index], _GEN_0[index]}),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:152:55, generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:209:24]
    .io_q  (_io_deq_bits_deq_bits_reg_io_q),
    .io_en (valid)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:146:28]
  );
  AsyncValidSync sink_valid_0 (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:168:33]
    .io_in  (1'h1),
    .io_out (_sink_valid_0_io_out),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_source_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:173:{42,45}]
  );
  AsyncValidSync sink_valid_1 (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:169:33]
    .io_in  (_sink_valid_0_io_out),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:168:33]
    .io_out (io_async_safe_ridx_valid),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_source_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:173:45, :174:42]
  );
  AsyncValidSync source_extend (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:171:31]
    .io_in  (io_async_safe_widx_valid),
    .io_out (_source_extend_io_out),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_source_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:173:45, :175:42]
  );
  AsyncValidSync source_valid (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:172:31]
    .io_in  (_source_extend_io_out),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:171:31]
    .io_out (_source_valid_io_out),
    .clock  (clock),
    .reset  (reset)
  );
  assign io_deq_valid = io_deq_valid_0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:162:29]
  assign io_deq_bits_gain = _io_deq_bits_deq_bits_reg_io_q[9:1];	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:207:25, :211:26]
  assign io_deq_bits_reset = _io_deq_bits_deq_bits_reg_io_q[0];	// @[generators/rocket-chip/src/main/scala/util/SynchronizerReg.scala:207:25, :211:26]
  assign io_async_ridx = ridx_gray;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:164:55]
  assign io_async_safe_sink_reset_n = ~reset;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:189:25]
endmodule

