// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ICache(
  input         clock,
                reset,
                auto_master_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_master_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [31:0] auto_master_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_master_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [2:0]  auto_master_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_master_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [31:0] auto_master_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_master_out_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
  input  [31:0] io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
                io_s1_paddr,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
  input         io_s1_kill,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
                io_s2_kill,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
  output        io_resp_valid,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
  output [31:0] io_resp_bits_data,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
  output        io_resp_bits_ae,	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
  input         io_invalidate	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
);

  wire         data_arrays_0_dout_en;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:582:46]
  wire         data_arrays_0_MPORT_1_en;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:562:32]
  wire         s1_tag_hit_1;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:506:26]
  wire         s1_tag_hit_0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:506:26]
  wire         data_arrays_0_MPORT_1_mask_0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:428:97]
  wire         refillError;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:422:43]
  wire         tag_array_tag_rdata_en;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:418:83]
  wire [5:0]   _tag_rdata_T_4;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:418:42]
  wire         io_req_ready;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:386:19]
  wire         masterNodeOut_a_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:377:35]
  wire [63:0]  _data_arrays_0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [41:0]  _tag_array_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire         _repl_way_v0_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         s0_ren = io_req_ready & io_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:386:19, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg          s1_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25]
  wire         s1_hit = s1_tag_hit_0 | s1_tag_hit_1;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:353:{35,40}, :506:26]
  reg          s2_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25]
  reg          s2_hit;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:356:23]
  reg          invalidated;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:359:24]
  reg          refill_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:360:29]
  wire         _refill_fire_T = auto_master_out_a_ready & masterNodeOut_a_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:377:35, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire         s2_miss = s2_valid & ~s2_hit & ~io_s2_kill;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :356:23, :370:{29,37,40}]
  reg          s2_request_refill_REG;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:377:45]
  assign masterNodeOut_a_valid = s2_miss & s2_request_refill_REG;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:370:37, :377:{35,45}]
  reg  [31:0]  refill_paddr;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31]
  wire         refill_one_beat = auto_master_out_d_valid & auto_master_out_d_bits_opcode[0];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36]
  assign io_req_ready = ~refill_one_beat;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39, :386:19]
  wire [12:0]  _beats1_decode_T_1 = 13'h3F << auto_master_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:235:71]
  wire [3:0]   beats1 = auto_master_out_d_bits_opcode[0] ? ~(_beats1_decode_T_1[5:2]) : 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:235:{46,71,76}]
  reg  [3:0]   counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire [3:0]   _counter1_T = counter - 4'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
  wire [3:0]   refill_cnt = beats1 & ~_counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :230:28, :234:{25,27}]
  wire         tag_array_MPORT_en = refill_one_beat & (counter == 4'h1 | beats1 == 4'h0) & auto_master_out_d_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39, :391:37, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{25,33,43}]
  wire [1:0]   _GEN = {_repl_way_v0_prng_io_out_0, data_arrays_0_MPORT_1_mask_0};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:428:97, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign _tag_rdata_T_4 = io_req_bits_addr[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:418:42]
  assign tag_array_tag_rdata_en = ~tag_array_MPORT_en & s0_ren;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:391:37, :418:{70,83}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg          accruedRefillError;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:420:31]
  assign refillError = auto_master_out_d_bits_corrupt | (|refill_cnt) & accruedRefillError;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:420:31, :422:{43,58,64}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:25]
  assign data_arrays_0_MPORT_1_mask_0 = ~_repl_way_v0_prng_io_out_0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:428:97, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  reg  [127:0] vb_array;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25]
  wire [127:0] _s1_vb_T_1 = vb_array >> io_s1_paddr[11:6];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25, :500:25, :851:21]
  assign s1_tag_hit_0 = _s1_vb_T_1[0] & _tag_array_RW0_rdata[19:0] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:485:30, :500:25, :506:{26,33}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
  wire [127:0] _s1_vb_T_5 = vb_array >> {122'h1, io_s1_paddr[11:6]};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25, :500:25, :851:21]
  assign s1_tag_hit_1 = _s1_vb_T_5[0] & _tag_array_RW0_rdata[40:21] == io_s1_paddr[31:12];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:485:30, :500:25, :506:{26,33}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:513:9]
    wire [1:0] _GEN_0 = {1'h0, s1_tag_hit_0} + {1'h0, s1_tag_hit_1};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:506:26, :513:50]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:513:9]
      if (~reset & ~(~s1_valid | ~(_GEN_0[1]))) begin	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25, :513:{9,10,39,50,115}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:513:9]
          $error("Assertion failed\n    at ICache.scala:513 assert(!(s1_valid || s1_slaveValid) || PopCount(s1_tag_hit zip s1_tag_disparity map { case (h, d) => h && !d }) <= 1.U)\n");	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:513:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:513:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:513:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign data_arrays_0_MPORT_1_en = refill_one_beat & ~invalidated;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:359:24, :383:39, :562:{32,35}]
  assign data_arrays_0_dout_en = ~data_arrays_0_MPORT_1_en & s0_ren;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:562:32, :582:{41,46}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg          s2_tag_hit_0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:597:29]
  reg          s2_tag_hit_1;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:597:29]
  reg  [31:0]  s2_dout_0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:604:26]
  reg  [31:0]  s2_dout_1;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:604:26]
  reg          s2_tl_error;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:607:30]
  wire [127:0] _vb_array_T_3 = 128'h1 << {121'h0, _repl_way_v0_prng_io_out_0, refill_paddr[11:6]};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31, :444:32, :851:21, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _s1_can_request_refill_T = s2_miss | refill_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:360:29, :370:37, :372:41]
  always @(posedge clock) begin
    if (reset) begin
      s1_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25]
      s2_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25]
      refill_valid <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:360:29]
      counter <= 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      vb_array <= 128'h0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25]
    end
    else begin
      s1_valid <= s0_ren;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      s2_valid <= s1_valid & ~io_s1_kill;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25, :355:{25,35,38}]
      refill_valid <= ~tag_array_MPORT_en & (_refill_fire_T | refill_valid);	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:360:29, :391:37, :822:{22,37}, :823:{22,37}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      if (auto_master_out_d_valid) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
        if (counter == 4'h0)	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25]
          counter <= beats1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27]
        else	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25]
          counter <= _counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
      end
      if (io_invalidate)	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:248:14]
        vb_array <= 128'h0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25]
      else if (refill_one_beat) begin	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39]
        if (tag_array_MPORT_en & ~invalidated)	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:359:24, :391:37, :444:{72,75}]
          vb_array <= vb_array | _vb_array_T_3;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25, :444:32]
        else	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:444:72]
          vb_array <= ~(~vb_array | _vb_array_T_3);	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25, :444:32]
      end
    end
    s2_hit <= s1_hit;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:353:40, :356:23]
    invalidated <= refill_valid & (io_invalidate | invalidated);	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:359:24, :360:29, :449:21, :451:17, :821:{24,38}]
    s2_request_refill_REG <= ~_s1_can_request_refill_T;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:372:{31,41}, :377:45]
    if (s1_valid & ~_s1_can_request_refill_T)	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25, :372:{31,41}, :378:54]
      refill_paddr <= io_s1_paddr;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31]
    if (refill_one_beat)	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39]
      accruedRefillError <= refillError;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:420:31, :422:43]
    if (s1_valid) begin	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25]
      s2_tag_hit_0 <= s1_tag_hit_0;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:506:26, :597:29]
      s2_tag_hit_1 <= s1_tag_hit_1;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:506:26, :597:29]
      s2_dout_0 <= _data_arrays_0_RW0_rdata[31:0];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:604:26, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
      s2_dout_1 <= _data_arrays_0_RW0_rdata[63:32];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:604:26, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
      s2_tl_error <= |{s1_tag_hit_1 & _tag_array_RW0_rdata[41], s1_tag_hit_0 & _tag_array_RW0_rdata[20]};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:506:26, :510:32, :607:{30,43,50}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:11];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        s1_valid = _RANDOM[4'h0][4];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:333:25]
        s2_valid = _RANDOM[4'h1][5];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25]
        s2_hit = _RANDOM[4'h1][6];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :356:23]
        invalidated = _RANDOM[4'h1][7];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :359:24]
        refill_valid = _RANDOM[4'h1][8];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :360:29]
        s2_request_refill_REG = _RANDOM[4'h1][11];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :377:45]
        refill_paddr = {_RANDOM[4'h1][31:12], _RANDOM[4'h2][11:0]};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :378:31]
        counter = _RANDOM[4'h3][15:12];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        accruedRefillError = _RANDOM[4'h3][16];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:420:31, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        vb_array = {_RANDOM[4'h3][31:17], _RANDOM[4'h4], _RANDOM[4'h5], _RANDOM[4'h6], _RANDOM[4'h7][16:0]};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:440:25, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        s2_tag_hit_0 = _RANDOM[4'h8][30];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:597:29]
        s2_tag_hit_1 = _RANDOM[4'h8][31];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:597:29]
        s2_dout_0 = _RANDOM[4'h9];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:604:26]
        s2_dout_1 = _RANDOM[4'hA];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:604:26]
        s2_tl_error = _RANDOM[4'hB][2];	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:607:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MaxPeriodFibonacciLFSR repl_way_v0_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock        (clock),
    .reset        (reset),
    .io_increment (_refill_fire_T),	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
    .io_out_0     (_repl_way_v0_prng_io_out_0),
    .io_out_1     (/* unused */),
    .io_out_2     (/* unused */),
    .io_out_3     (/* unused */),
    .io_out_4     (/* unused */),
    .io_out_5     (/* unused */),
    .io_out_6     (/* unused */),
    .io_out_7     (/* unused */),
    .io_out_8     (/* unused */),
    .io_out_9     (/* unused */),
    .io_out_10    (/* unused */),
    .io_out_11    (/* unused */),
    .io_out_12    (/* unused */),
    .io_out_13    (/* unused */),
    .io_out_14    (/* unused */),
    .io_out_15    (/* unused */)
  );
  tag_array_0 tag_array (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (tag_array_MPORT_en ? refill_paddr[11:6] : _tag_rdata_T_4),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31, :391:37, :418:42, :851:21, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_en    (tag_array_tag_rdata_en | tag_array_MPORT_en),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:391:37, :418:83, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39]
    .RW0_wdata ({refillError, refill_paddr[31:12], refillError, refill_paddr[31:12]}),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31, :380:33, :422:43, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_tag_array_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );
  data_arrays_0_0 data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? {refill_paddr[11:6], refill_cnt} : io_req_bits_addr[11:2]),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31, :383:39, :557:31, :566:{10,67}, :851:21, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:234:25]
    .RW0_en    (data_arrays_0_dout_en | data_arrays_0_MPORT_1_en),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:562:32, :582:46, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:383:39]
    .RW0_wdata ({2{auto_master_out_d_bits_data}}),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_data_arrays_0_RW0_rdata),
    .RW0_wmask (_GEN)	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );
  assign auto_master_out_a_valid = masterNodeOut_a_valid;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:377:35]
  assign auto_master_out_a_bits_address = {refill_paddr[31:6], 6'h0};	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:378:31, :434:40, :761:64]
  assign io_resp_valid = s2_valid & s2_hit;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:355:25, :356:23, :651:33]
  assign io_resp_bits_data = (s2_tag_hit_0 ? s2_dout_0 : 32'h0) | (s2_tag_hit_1 ? s2_dout_1 : 32'h0);	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:597:29, :604:26, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:469:15, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_resp_bits_ae = s2_tl_error;	// @[generators/rocket-chip/src/main/scala/rocket/ICache.scala:607:30]
endmodule

