// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ModemLUT_4(
  input         clock,
                reset,
  output [9:0]  io_out_0,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_1,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_2,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_3,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_4,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_5,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_6,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_7,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_8,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_9,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_10,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_11,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_12,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_13,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_14,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_15,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_16,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_17,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_18,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_19,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_20,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_21,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_22,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_23,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_24,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_25,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_26,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_27,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_28,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_29,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_30,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
                io_out_31,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
  input         io_lutCmd_valid,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
  input  [3:0]  io_lutCmd_bits_lut,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
  input  [5:0]  io_lutCmd_bits_address,	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
  input  [21:0] io_lutCmd_bits_value	// @[generators/baseband/src/main/scala/modem/LUT.scala:37:14]
);

  reg  [9:0] reg_0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_1;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_2;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_3;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_4;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_5;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_6;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_7;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_8;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_9;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_10;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_11;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_12;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_13;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_14;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_15;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_16;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_17;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_18;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_19;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_20;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_21;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_22;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_23;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_24;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_25;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_26;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_27;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_28;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_29;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_30;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  reg  [9:0] reg_31;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  wire       _GEN = io_lutCmd_valid & io_lutCmd_bits_lut == 4'h4;	// @[generators/baseband/src/main/scala/modem/LUT.scala:44:{25,47}]
  always @(posedge clock) begin
    if (reset) begin
      reg_0 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_1 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_2 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_3 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_4 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_5 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_6 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_7 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_8 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_9 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_10 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_11 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_12 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_13 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_14 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_15 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_16 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_17 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_18 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_19 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_20 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_21 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_22 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_23 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_24 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_25 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_26 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_27 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_28 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_29 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_30 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
      reg_31 <= 10'h0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:{20,46}]
    end
    else begin
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h0)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_0 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h1)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_1 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h2)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_2 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h3)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_3 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h4)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_4 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h5)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_5 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h6)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_6 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h7)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_7 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h8)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_8 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h9)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_9 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'hA)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_10 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'hB)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_11 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'hC)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_12 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'hD)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_13 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'hE)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_14 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'hF)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_15 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h10)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_16 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h11)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_17 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h12)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_18 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h13)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_19 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h14)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_20 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h15)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_21 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h16)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_22 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h17)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_23 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h18)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_24 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h19)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_25 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h1A)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_26 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h1B)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_27 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h1C)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_28 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h1D)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_29 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & io_lutCmd_bits_address[4:0] == 5'h1E)	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_30 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
      if (_GEN & (&(io_lutCmd_bits_address[4:0])))	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :44:{25,61}, :45:33]
        reg_31 <= io_lutCmd_bits_value[9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20, :45:56]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:9];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'hA; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        reg_0 = _RANDOM[4'h0][9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_1 = _RANDOM[4'h0][19:10];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_2 = _RANDOM[4'h0][29:20];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_3 = {_RANDOM[4'h0][31:30], _RANDOM[4'h1][7:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_4 = _RANDOM[4'h1][17:8];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_5 = _RANDOM[4'h1][27:18];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_6 = {_RANDOM[4'h1][31:28], _RANDOM[4'h2][5:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_7 = _RANDOM[4'h2][15:6];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_8 = _RANDOM[4'h2][25:16];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_9 = {_RANDOM[4'h2][31:26], _RANDOM[4'h3][3:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_10 = _RANDOM[4'h3][13:4];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_11 = _RANDOM[4'h3][23:14];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_12 = {_RANDOM[4'h3][31:24], _RANDOM[4'h4][1:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_13 = _RANDOM[4'h4][11:2];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_14 = _RANDOM[4'h4][21:12];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_15 = _RANDOM[4'h4][31:22];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_16 = _RANDOM[4'h5][9:0];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_17 = _RANDOM[4'h5][19:10];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_18 = _RANDOM[4'h5][29:20];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_19 = {_RANDOM[4'h5][31:30], _RANDOM[4'h6][7:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_20 = _RANDOM[4'h6][17:8];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_21 = _RANDOM[4'h6][27:18];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_22 = {_RANDOM[4'h6][31:28], _RANDOM[4'h7][5:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_23 = _RANDOM[4'h7][15:6];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_24 = _RANDOM[4'h7][25:16];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_25 = {_RANDOM[4'h7][31:26], _RANDOM[4'h8][3:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_26 = _RANDOM[4'h8][13:4];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_27 = _RANDOM[4'h8][23:14];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_28 = {_RANDOM[4'h8][31:24], _RANDOM[4'h9][1:0]};	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_29 = _RANDOM[4'h9][11:2];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_30 = _RANDOM[4'h9][21:12];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
        reg_31 = _RANDOM[4'h9][31:22];	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_0 = reg_0;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_1 = reg_1;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_2 = reg_2;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_3 = reg_3;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_4 = reg_4;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_5 = reg_5;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_6 = reg_6;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_7 = reg_7;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_8 = reg_8;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_9 = reg_9;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_10 = reg_10;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_11 = reg_11;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_12 = reg_12;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_13 = reg_13;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_14 = reg_14;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_15 = reg_15;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_16 = reg_16;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_17 = reg_17;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_18 = reg_18;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_19 = reg_19;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_20 = reg_20;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_21 = reg_21;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_22 = reg_22;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_23 = reg_23;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_24 = reg_24;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_25 = reg_25;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_26 = reg_26;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_27 = reg_27;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_28 = reg_28;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_29 = reg_29;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_30 = reg_30;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
  assign io_out_31 = reg_31;	// @[generators/baseband/src/main/scala/modem/LUT.scala:42:20]
endmodule

