// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RocketTile(
  input         clock,
                reset,
                auto_buffer_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_buffer_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [2:0]  auto_buffer_out_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [1:0]  auto_buffer_out_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [31:0] auto_buffer_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [3:0]  auto_buffer_out_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [31:0] auto_buffer_out_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_buffer_out_b_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_buffer_out_b_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [2:0]  auto_buffer_out_b_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [1:0]  auto_buffer_out_b_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [2:0]  auto_buffer_out_b_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [1:0]  auto_buffer_out_b_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [31:0] auto_buffer_out_b_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [3:0]  auto_buffer_out_b_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_buffer_out_b_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_c_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_buffer_out_c_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [2:0]  auto_buffer_out_c_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_c_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_c_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [1:0]  auto_buffer_out_c_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [31:0] auto_buffer_out_c_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_c_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_buffer_out_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_buffer_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [2:0]  auto_buffer_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [1:0]  auto_buffer_out_d_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [2:0]  auto_buffer_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [1:0]  auto_buffer_out_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_buffer_out_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [31:0] auto_buffer_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_buffer_out_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_buffer_out_e_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_buffer_out_e_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [1:0]  auto_buffer_out_e_bits_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_wfi_out_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_int_local_in_2_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_local_in_1_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_local_in_1_1,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_local_in_0_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_hartid_in	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
);

  wire        _core_io_imem_might_request;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_imem_req_valid;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [31:0] _core_io_imem_req_bits_pc;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_imem_req_bits_speculative;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_imem_resp_ready;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_imem_btb_update_valid;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_imem_bht_update_valid;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_imem_flush_icache;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_dmem_req_valid;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [31:0] _core_io_dmem_req_bits_addr;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [5:0]  _core_io_dmem_req_bits_tag;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [4:0]  _core_io_dmem_req_bits_cmd;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [1:0]  _core_io_dmem_req_bits_size;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_dmem_req_bits_signed;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_dmem_req_bits_dv;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_dmem_s1_kill;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [31:0] _core_io_dmem_s1_data_data;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_ptw_status_debug;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire [31:0] _core_io_ptw_customCSRs_csrs_0_value;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _core_io_wfi;	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  wire        _ptw_io_requestor_0_status_debug;	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
  wire        _ptw_io_requestor_1_status_debug;	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
  wire [31:0] _ptw_io_requestor_1_customCSRs_csrs_0_value;	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
  wire        _dcacheArb_io_requestor_0_req_ready;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_nack;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [5:0]  _dcacheArb_io_requestor_0_resp_bits_tag;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [31:0] _dcacheArb_io_requestor_0_resp_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_resp_bits_replay;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_resp_bits_has_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [31:0] _dcacheArb_io_requestor_0_resp_bits_data_word_bypass;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_replay_next;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ma_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ma_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_xcpt_pf_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_xcpt_pf_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ae_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_s2_xcpt_ae_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_ordered;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_perf_release;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_requestor_0_perf_grant;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_mem_req_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [31:0] _dcacheArb_io_mem_req_bits_addr;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [5:0]  _dcacheArb_io_mem_req_bits_tag;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [4:0]  _dcacheArb_io_mem_req_bits_cmd;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [1:0]  _dcacheArb_io_mem_req_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_mem_req_bits_signed;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_mem_req_bits_dv;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _dcacheArb_io_mem_s1_kill;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire [31:0] _dcacheArb_io_mem_s1_data_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
  wire        _frontend_auto_icache_master_out_a_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire [31:0] _frontend_auto_icache_master_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_cpu_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire [31:0] _frontend_io_cpu_resp_bits_pc;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire [31:0] _frontend_io_cpu_resp_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_cpu_resp_bits_xcpt_pf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_cpu_resp_bits_xcpt_gf_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_cpu_resp_bits_xcpt_ae_inst;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_cpu_resp_bits_replay;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_ptw_req_bits_bits_need_gpa;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _frontend_io_ptw_req_bits_bits_stage2;	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
  wire        _dcache_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [2:0]  _dcache_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [2:0]  _dcache_auto_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [2:0]  _dcache_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [31:0] _dcache_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [3:0]  _dcache_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [31:0] _dcache_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_auto_out_b_ready;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_auto_out_c_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [2:0]  _dcache_auto_out_c_bits_opcode;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [2:0]  _dcache_auto_out_c_bits_param;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [2:0]  _dcache_auto_out_c_bits_size;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_auto_out_c_bits_source;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [31:0] _dcache_auto_out_c_bits_address;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [31:0] _dcache_auto_out_c_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_auto_out_e_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [1:0]  _dcache_auto_out_e_bits_sink;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_req_ready;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_nack;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_resp_valid;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [5:0]  _dcache_io_cpu_resp_bits_tag;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [31:0] _dcache_io_cpu_resp_bits_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_resp_bits_replay;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_resp_bits_has_data;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire [31:0] _dcache_io_cpu_resp_bits_data_word_bypass;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_replay_next;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_xcpt_ma_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_xcpt_ma_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_xcpt_pf_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_xcpt_pf_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_xcpt_ae_ld;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_s2_xcpt_ae_st;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_ordered;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_perf_release;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_cpu_perf_grant;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_ptw_req_bits_bits_need_gpa;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _dcache_io_ptw_req_bits_bits_stage2;	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  wire        _intXbar_auto_int_out_0;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
  wire        _intXbar_auto_int_out_1;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
  wire        _intXbar_auto_int_out_2;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
  wire        _intXbar_auto_int_out_3;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
  wire        _tlMasterXbar_auto_in_1_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_1_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [2:0]  _tlMasterXbar_auto_in_1_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [2:0]  _tlMasterXbar_auto_in_1_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [31:0] _tlMasterXbar_auto_in_1_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_1_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_b_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [1:0]  _tlMasterXbar_auto_in_0_b_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [2:0]  _tlMasterXbar_auto_in_0_b_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_b_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [31:0] _tlMasterXbar_auto_in_0_b_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_c_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [2:0]  _tlMasterXbar_auto_in_0_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [1:0]  _tlMasterXbar_auto_in_0_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [2:0]  _tlMasterXbar_auto_in_0_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [1:0]  _tlMasterXbar_auto_in_0_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire [31:0] _tlMasterXbar_auto_in_0_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  wire        _tlMasterXbar_auto_in_0_e_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
  reg         wfiNodeOut_0_REG;	// @[generators/rocket-chip/src/main/scala/tile/Interrupts.scala:126:36]
  always @(posedge clock) begin
    if (reset)
      wfiNodeOut_0_REG <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tile/Interrupts.scala:126:36]
    else
      wfiNodeOut_0_REG <= _core_io_wfi;	// @[generators/rocket-chip/src/main/scala/tile/Interrupts.scala:126:36, generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        wfiNodeOut_0_REG = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/rocket-chip/src/main/scala/tile/Interrupts.scala:126:36]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLXbar_7 tlMasterXbar (	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .clock                    (clock),
    .reset                    (reset),
    .auto_in_1_a_ready        (_tlMasterXbar_auto_in_1_a_ready),
    .auto_in_1_a_valid        (_frontend_auto_icache_master_out_a_valid),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .auto_in_1_a_bits_address (_frontend_auto_icache_master_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .auto_in_1_d_valid        (_tlMasterXbar_auto_in_1_d_valid),
    .auto_in_1_d_bits_opcode  (_tlMasterXbar_auto_in_1_d_bits_opcode),
    .auto_in_1_d_bits_size    (_tlMasterXbar_auto_in_1_d_bits_size),
    .auto_in_1_d_bits_data    (_tlMasterXbar_auto_in_1_d_bits_data),
    .auto_in_1_d_bits_corrupt (_tlMasterXbar_auto_in_1_d_bits_corrupt),
    .auto_in_0_a_ready        (_tlMasterXbar_auto_in_0_a_ready),
    .auto_in_0_a_valid        (_dcache_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_opcode  (_dcache_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_param   (_dcache_auto_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_size    (_dcache_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_source  (_dcache_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_address (_dcache_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_mask    (_dcache_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_a_bits_data    (_dcache_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_b_ready        (_dcache_auto_out_b_ready),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_b_valid        (_tlMasterXbar_auto_in_0_b_valid),
    .auto_in_0_b_bits_param   (_tlMasterXbar_auto_in_0_b_bits_param),
    .auto_in_0_b_bits_size    (_tlMasterXbar_auto_in_0_b_bits_size),
    .auto_in_0_b_bits_source  (_tlMasterXbar_auto_in_0_b_bits_source),
    .auto_in_0_b_bits_address (_tlMasterXbar_auto_in_0_b_bits_address),
    .auto_in_0_c_ready        (_tlMasterXbar_auto_in_0_c_ready),
    .auto_in_0_c_valid        (_dcache_auto_out_c_valid),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_c_bits_opcode  (_dcache_auto_out_c_bits_opcode),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_c_bits_param   (_dcache_auto_out_c_bits_param),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_c_bits_size    (_dcache_auto_out_c_bits_size),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_c_bits_source  (_dcache_auto_out_c_bits_source),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_c_bits_address (_dcache_auto_out_c_bits_address),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_c_bits_data    (_dcache_auto_out_c_bits_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_d_ready        (_dcache_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_d_valid        (_tlMasterXbar_auto_in_0_d_valid),
    .auto_in_0_d_bits_opcode  (_tlMasterXbar_auto_in_0_d_bits_opcode),
    .auto_in_0_d_bits_param   (_tlMasterXbar_auto_in_0_d_bits_param),
    .auto_in_0_d_bits_size    (_tlMasterXbar_auto_in_0_d_bits_size),
    .auto_in_0_d_bits_source  (_tlMasterXbar_auto_in_0_d_bits_source),
    .auto_in_0_d_bits_sink    (_tlMasterXbar_auto_in_0_d_bits_sink),
    .auto_in_0_d_bits_denied  (_tlMasterXbar_auto_in_0_d_bits_denied),
    .auto_in_0_d_bits_data    (_tlMasterXbar_auto_in_0_d_bits_data),
    .auto_in_0_e_ready        (_tlMasterXbar_auto_in_0_e_ready),
    .auto_in_0_e_valid        (_dcache_auto_out_e_valid),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_in_0_e_bits_sink    (_dcache_auto_out_e_bits_sink),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .auto_out_a_ready         (auto_buffer_out_a_ready),
    .auto_out_a_valid         (auto_buffer_out_a_valid),
    .auto_out_a_bits_opcode   (auto_buffer_out_a_bits_opcode),
    .auto_out_a_bits_param    (auto_buffer_out_a_bits_param),
    .auto_out_a_bits_size     (auto_buffer_out_a_bits_size),
    .auto_out_a_bits_source   (auto_buffer_out_a_bits_source),
    .auto_out_a_bits_address  (auto_buffer_out_a_bits_address),
    .auto_out_a_bits_mask     (auto_buffer_out_a_bits_mask),
    .auto_out_a_bits_data     (auto_buffer_out_a_bits_data),
    .auto_out_b_ready         (auto_buffer_out_b_ready),
    .auto_out_b_valid         (auto_buffer_out_b_valid),
    .auto_out_b_bits_opcode   (auto_buffer_out_b_bits_opcode),
    .auto_out_b_bits_param    (auto_buffer_out_b_bits_param),
    .auto_out_b_bits_size     (auto_buffer_out_b_bits_size),
    .auto_out_b_bits_source   (auto_buffer_out_b_bits_source),
    .auto_out_b_bits_address  (auto_buffer_out_b_bits_address),
    .auto_out_b_bits_mask     (auto_buffer_out_b_bits_mask),
    .auto_out_b_bits_corrupt  (auto_buffer_out_b_bits_corrupt),
    .auto_out_c_ready         (auto_buffer_out_c_ready),
    .auto_out_c_valid         (auto_buffer_out_c_valid),
    .auto_out_c_bits_opcode   (auto_buffer_out_c_bits_opcode),
    .auto_out_c_bits_param    (auto_buffer_out_c_bits_param),
    .auto_out_c_bits_size     (auto_buffer_out_c_bits_size),
    .auto_out_c_bits_source   (auto_buffer_out_c_bits_source),
    .auto_out_c_bits_address  (auto_buffer_out_c_bits_address),
    .auto_out_c_bits_data     (auto_buffer_out_c_bits_data),
    .auto_out_d_ready         (auto_buffer_out_d_ready),
    .auto_out_d_valid         (auto_buffer_out_d_valid),
    .auto_out_d_bits_opcode   (auto_buffer_out_d_bits_opcode),
    .auto_out_d_bits_param    (auto_buffer_out_d_bits_param),
    .auto_out_d_bits_size     (auto_buffer_out_d_bits_size),
    .auto_out_d_bits_source   (auto_buffer_out_d_bits_source),
    .auto_out_d_bits_sink     (auto_buffer_out_d_bits_sink),
    .auto_out_d_bits_denied   (auto_buffer_out_d_bits_denied),
    .auto_out_d_bits_data     (auto_buffer_out_d_bits_data),
    .auto_out_d_bits_corrupt  (auto_buffer_out_d_bits_corrupt),
    .auto_out_e_ready         (auto_buffer_out_e_ready),
    .auto_out_e_valid         (auto_buffer_out_e_valid),
    .auto_out_e_bits_sink     (auto_buffer_out_e_bits_sink)
  );
  IntXbar_1 intXbar (	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
    .auto_int_in_2_0 (auto_int_local_in_2_0),
    .auto_int_in_1_0 (auto_int_local_in_1_0),
    .auto_int_in_1_1 (auto_int_local_in_1_1),
    .auto_int_in_0_0 (auto_int_local_in_0_0),
    .auto_int_out_0  (_intXbar_auto_int_out_0),
    .auto_int_out_1  (_intXbar_auto_int_out_1),
    .auto_int_out_2  (_intXbar_auto_int_out_2),
    .auto_int_out_3  (_intXbar_auto_int_out_3)
  );
  DCache dcache (	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .clock                             (clock),
    .reset                             (reset),
    .auto_out_a_ready                  (_tlMasterXbar_auto_in_0_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_a_valid                  (_dcache_auto_out_a_valid),
    .auto_out_a_bits_opcode            (_dcache_auto_out_a_bits_opcode),
    .auto_out_a_bits_param             (_dcache_auto_out_a_bits_param),
    .auto_out_a_bits_size              (_dcache_auto_out_a_bits_size),
    .auto_out_a_bits_source            (_dcache_auto_out_a_bits_source),
    .auto_out_a_bits_address           (_dcache_auto_out_a_bits_address),
    .auto_out_a_bits_mask              (_dcache_auto_out_a_bits_mask),
    .auto_out_a_bits_data              (_dcache_auto_out_a_bits_data),
    .auto_out_b_ready                  (_dcache_auto_out_b_ready),
    .auto_out_b_valid                  (_tlMasterXbar_auto_in_0_b_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_b_bits_param             (_tlMasterXbar_auto_in_0_b_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_b_bits_size              (_tlMasterXbar_auto_in_0_b_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_b_bits_source            (_tlMasterXbar_auto_in_0_b_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_b_bits_address           (_tlMasterXbar_auto_in_0_b_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_c_ready                  (_tlMasterXbar_auto_in_0_c_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_c_valid                  (_dcache_auto_out_c_valid),
    .auto_out_c_bits_opcode            (_dcache_auto_out_c_bits_opcode),
    .auto_out_c_bits_param             (_dcache_auto_out_c_bits_param),
    .auto_out_c_bits_size              (_dcache_auto_out_c_bits_size),
    .auto_out_c_bits_source            (_dcache_auto_out_c_bits_source),
    .auto_out_c_bits_address           (_dcache_auto_out_c_bits_address),
    .auto_out_c_bits_data              (_dcache_auto_out_c_bits_data),
    .auto_out_d_ready                  (_dcache_auto_out_d_ready),
    .auto_out_d_valid                  (_tlMasterXbar_auto_in_0_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_opcode            (_tlMasterXbar_auto_in_0_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_param             (_tlMasterXbar_auto_in_0_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_size              (_tlMasterXbar_auto_in_0_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_source            (_tlMasterXbar_auto_in_0_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_sink              (_tlMasterXbar_auto_in_0_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_denied            (_tlMasterXbar_auto_in_0_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_d_bits_data              (_tlMasterXbar_auto_in_0_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_e_ready                  (_tlMasterXbar_auto_in_0_e_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_out_e_valid                  (_dcache_auto_out_e_valid),
    .auto_out_e_bits_sink              (_dcache_auto_out_e_bits_sink),
    .io_cpu_req_ready                  (_dcache_io_cpu_req_ready),
    .io_cpu_req_valid                  (_dcacheArb_io_mem_req_valid),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_req_bits_addr              (_dcacheArb_io_mem_req_bits_addr),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_req_bits_tag               (_dcacheArb_io_mem_req_bits_tag),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_req_bits_cmd               (_dcacheArb_io_mem_req_bits_cmd),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_req_bits_size              (_dcacheArb_io_mem_req_bits_size),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_req_bits_signed            (_dcacheArb_io_mem_req_bits_signed),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_req_bits_dv                (_dcacheArb_io_mem_req_bits_dv),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_s1_kill                    (_dcacheArb_io_mem_s1_kill),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_s1_data_data               (_dcacheArb_io_mem_s1_data_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_cpu_s1_data_mask               (4'h0),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18, generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43, :286:25, generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19, generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_s2_nack                    (_dcache_io_cpu_s2_nack),
    .io_cpu_resp_valid                 (_dcache_io_cpu_resp_valid),
    .io_cpu_resp_bits_addr             (/* unused */),
    .io_cpu_resp_bits_tag              (_dcache_io_cpu_resp_bits_tag),
    .io_cpu_resp_bits_cmd              (/* unused */),
    .io_cpu_resp_bits_size             (/* unused */),
    .io_cpu_resp_bits_signed           (/* unused */),
    .io_cpu_resp_bits_dprv             (/* unused */),
    .io_cpu_resp_bits_dv               (/* unused */),
    .io_cpu_resp_bits_data             (_dcache_io_cpu_resp_bits_data),
    .io_cpu_resp_bits_mask             (/* unused */),
    .io_cpu_resp_bits_replay           (_dcache_io_cpu_resp_bits_replay),
    .io_cpu_resp_bits_has_data         (_dcache_io_cpu_resp_bits_has_data),
    .io_cpu_resp_bits_data_word_bypass (_dcache_io_cpu_resp_bits_data_word_bypass),
    .io_cpu_resp_bits_data_raw         (/* unused */),
    .io_cpu_resp_bits_store_data       (/* unused */),
    .io_cpu_replay_next                (_dcache_io_cpu_replay_next),
    .io_cpu_s2_xcpt_ma_ld              (_dcache_io_cpu_s2_xcpt_ma_ld),
    .io_cpu_s2_xcpt_ma_st              (_dcache_io_cpu_s2_xcpt_ma_st),
    .io_cpu_s2_xcpt_pf_ld              (_dcache_io_cpu_s2_xcpt_pf_ld),
    .io_cpu_s2_xcpt_pf_st              (_dcache_io_cpu_s2_xcpt_pf_st),
    .io_cpu_s2_xcpt_ae_ld              (_dcache_io_cpu_s2_xcpt_ae_ld),
    .io_cpu_s2_xcpt_ae_st              (_dcache_io_cpu_s2_xcpt_ae_st),
    .io_cpu_ordered                    (_dcache_io_cpu_ordered),
    .io_cpu_perf_release               (_dcache_io_cpu_perf_release),
    .io_cpu_perf_grant                 (_dcache_io_cpu_perf_grant),
    .io_ptw_req_bits_bits_need_gpa     (_dcache_io_ptw_req_bits_bits_need_gpa),
    .io_ptw_req_bits_bits_stage2       (_dcache_io_ptw_req_bits_bits_stage2),
    .io_ptw_status_debug               (_ptw_io_requestor_0_status_debug)	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
  );
  Frontend frontend (	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .clock                                 (clock),
    .reset                                 (reset),
    .auto_icache_master_out_a_ready        (_tlMasterXbar_auto_in_1_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_icache_master_out_a_valid        (_frontend_auto_icache_master_out_a_valid),
    .auto_icache_master_out_a_bits_address (_frontend_auto_icache_master_out_a_bits_address),
    .auto_icache_master_out_d_valid        (_tlMasterXbar_auto_in_1_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_icache_master_out_d_bits_opcode  (_tlMasterXbar_auto_in_1_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_icache_master_out_d_bits_size    (_tlMasterXbar_auto_in_1_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_icache_master_out_d_bits_data    (_tlMasterXbar_auto_in_1_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .auto_icache_master_out_d_bits_corrupt (_tlMasterXbar_auto_in_1_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:56:42]
    .io_cpu_might_request                  (_core_io_imem_might_request),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_req_valid                      (_core_io_imem_req_valid),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_req_bits_pc                    (_core_io_imem_req_bits_pc),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_req_bits_speculative           (_core_io_imem_req_bits_speculative),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_resp_ready                     (_core_io_imem_resp_ready),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_resp_valid                     (_frontend_io_cpu_resp_valid),
    .io_cpu_resp_bits_pc                   (_frontend_io_cpu_resp_bits_pc),
    .io_cpu_resp_bits_data                 (_frontend_io_cpu_resp_bits_data),
    .io_cpu_resp_bits_xcpt_pf_inst         (_frontend_io_cpu_resp_bits_xcpt_pf_inst),
    .io_cpu_resp_bits_xcpt_gf_inst         (_frontend_io_cpu_resp_bits_xcpt_gf_inst),
    .io_cpu_resp_bits_xcpt_ae_inst         (_frontend_io_cpu_resp_bits_xcpt_ae_inst),
    .io_cpu_resp_bits_replay               (_frontend_io_cpu_resp_bits_replay),
    .io_cpu_btb_update_valid               (_core_io_imem_btb_update_valid),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_bht_update_valid               (_core_io_imem_bht_update_valid),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_cpu_flush_icache                   (_core_io_imem_flush_icache),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_ptw_req_bits_bits_need_gpa         (_frontend_io_ptw_req_bits_bits_need_gpa),
    .io_ptw_req_bits_bits_stage2           (_frontend_io_ptw_req_bits_bits_stage2),
    .io_ptw_status_debug                   (_ptw_io_requestor_1_status_debug),	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
    .io_ptw_customCSRs_csrs_0_value        (_ptw_io_requestor_1_customCSRs_csrs_0_value)	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
  );
  HellaCacheArbiter dcacheArb (	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_requestor_0_req_ready                  (_dcacheArb_io_requestor_0_req_ready),
    .io_requestor_0_req_valid                  (_core_io_dmem_req_valid),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_req_bits_addr              (_core_io_dmem_req_bits_addr),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_req_bits_tag               (_core_io_dmem_req_bits_tag),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_req_bits_cmd               (_core_io_dmem_req_bits_cmd),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_req_bits_size              (_core_io_dmem_req_bits_size),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_req_bits_signed            (_core_io_dmem_req_bits_signed),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_req_bits_dv                (_core_io_dmem_req_bits_dv),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_s1_kill                    (_core_io_dmem_s1_kill),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_s1_data_data               (_core_io_dmem_s1_data_data),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_requestor_0_s2_nack                    (_dcacheArb_io_requestor_0_s2_nack),
    .io_requestor_0_resp_valid                 (_dcacheArb_io_requestor_0_resp_valid),
    .io_requestor_0_resp_bits_tag              (_dcacheArb_io_requestor_0_resp_bits_tag),
    .io_requestor_0_resp_bits_data             (_dcacheArb_io_requestor_0_resp_bits_data),
    .io_requestor_0_resp_bits_replay           (_dcacheArb_io_requestor_0_resp_bits_replay),
    .io_requestor_0_resp_bits_has_data         (_dcacheArb_io_requestor_0_resp_bits_has_data),
    .io_requestor_0_resp_bits_data_word_bypass (_dcacheArb_io_requestor_0_resp_bits_data_word_bypass),
    .io_requestor_0_replay_next                (_dcacheArb_io_requestor_0_replay_next),
    .io_requestor_0_s2_xcpt_ma_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ma_ld),
    .io_requestor_0_s2_xcpt_ma_st              (_dcacheArb_io_requestor_0_s2_xcpt_ma_st),
    .io_requestor_0_s2_xcpt_pf_ld              (_dcacheArb_io_requestor_0_s2_xcpt_pf_ld),
    .io_requestor_0_s2_xcpt_pf_st              (_dcacheArb_io_requestor_0_s2_xcpt_pf_st),
    .io_requestor_0_s2_xcpt_ae_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ae_ld),
    .io_requestor_0_s2_xcpt_ae_st              (_dcacheArb_io_requestor_0_s2_xcpt_ae_st),
    .io_requestor_0_ordered                    (_dcacheArb_io_requestor_0_ordered),
    .io_requestor_0_perf_release               (_dcacheArb_io_requestor_0_perf_release),
    .io_requestor_0_perf_grant                 (_dcacheArb_io_requestor_0_perf_grant),
    .io_mem_req_ready                          (_dcache_io_cpu_req_ready),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_req_valid                          (_dcacheArb_io_mem_req_valid),
    .io_mem_req_bits_addr                      (_dcacheArb_io_mem_req_bits_addr),
    .io_mem_req_bits_tag                       (_dcacheArb_io_mem_req_bits_tag),
    .io_mem_req_bits_cmd                       (_dcacheArb_io_mem_req_bits_cmd),
    .io_mem_req_bits_size                      (_dcacheArb_io_mem_req_bits_size),
    .io_mem_req_bits_signed                    (_dcacheArb_io_mem_req_bits_signed),
    .io_mem_req_bits_dv                        (_dcacheArb_io_mem_req_bits_dv),
    .io_mem_s1_kill                            (_dcacheArb_io_mem_s1_kill),
    .io_mem_s1_data_data                       (_dcacheArb_io_mem_s1_data_data),
    .io_mem_s2_nack                            (_dcache_io_cpu_s2_nack),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_resp_valid                         (_dcache_io_cpu_resp_valid),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_resp_bits_tag                      (_dcache_io_cpu_resp_bits_tag),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_resp_bits_data                     (_dcache_io_cpu_resp_bits_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_resp_bits_replay                   (_dcache_io_cpu_resp_bits_replay),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_resp_bits_has_data                 (_dcache_io_cpu_resp_bits_has_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_resp_bits_data_word_bypass         (_dcache_io_cpu_resp_bits_data_word_bypass),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_replay_next                        (_dcache_io_cpu_replay_next),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_s2_xcpt_ma_ld                      (_dcache_io_cpu_s2_xcpt_ma_ld),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_s2_xcpt_ma_st                      (_dcache_io_cpu_s2_xcpt_ma_st),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_s2_xcpt_pf_ld                      (_dcache_io_cpu_s2_xcpt_pf_ld),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_s2_xcpt_pf_st                      (_dcache_io_cpu_s2_xcpt_pf_st),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_s2_xcpt_ae_ld                      (_dcache_io_cpu_s2_xcpt_ae_ld),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_s2_xcpt_ae_st                      (_dcache_io_cpu_s2_xcpt_ae_st),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_ordered                            (_dcache_io_cpu_ordered),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_perf_release                       (_dcache_io_cpu_perf_release),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_mem_perf_grant                         (_dcache_io_cpu_perf_grant)	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
  );
  PTW ptw (	// @[generators/rocket-chip/src/main/scala/rocket/PTW.scala:805:19]
    .clock                                  (clock),
    .io_requestor_0_req_bits_bits_need_gpa  (_dcache_io_ptw_req_bits_bits_need_gpa),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_requestor_0_req_bits_bits_stage2    (_dcache_io_ptw_req_bits_bits_stage2),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:269:43]
    .io_requestor_0_status_debug            (_ptw_io_requestor_0_status_debug),
    .io_requestor_1_req_bits_bits_need_gpa  (_frontend_io_ptw_req_bits_bits_need_gpa),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_requestor_1_req_bits_bits_stage2    (_frontend_io_ptw_req_bits_bits_stage2),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_requestor_1_status_debug            (_ptw_io_requestor_1_status_debug),
    .io_requestor_1_customCSRs_csrs_0_value (_ptw_io_requestor_1_customCSRs_csrs_0_value),
    .io_dpath_status_debug                  (_core_io_ptw_status_debug),	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .io_dpath_customCSRs_csrs_0_value       (_core_io_ptw_customCSRs_csrs_0_value)	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
  );
  Rocket core (	// @[generators/rocket-chip/src/main/scala/tile/RocketTile.scala:133:20]
    .clock                              (clock),
    .reset                              (reset),
    .io_hartid                          (auto_hartid_in),
    .io_interrupts_debug                (_intXbar_auto_int_out_0),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
    .io_interrupts_mtip                 (_intXbar_auto_int_out_2),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
    .io_interrupts_msip                 (_intXbar_auto_int_out_1),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
    .io_interrupts_meip                 (_intXbar_auto_int_out_3),	// @[generators/rocket-chip/src/main/scala/subsystem/HierarchicalElement.scala:58:37]
    .io_imem_might_request              (_core_io_imem_might_request),
    .io_imem_req_valid                  (_core_io_imem_req_valid),
    .io_imem_req_bits_pc                (_core_io_imem_req_bits_pc),
    .io_imem_req_bits_speculative       (_core_io_imem_req_bits_speculative),
    .io_imem_resp_ready                 (_core_io_imem_resp_ready),
    .io_imem_resp_valid                 (_frontend_io_cpu_resp_valid),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_resp_bits_pc               (_frontend_io_cpu_resp_bits_pc),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_resp_bits_data             (_frontend_io_cpu_resp_bits_data),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_resp_bits_xcpt_pf_inst     (_frontend_io_cpu_resp_bits_xcpt_pf_inst),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_resp_bits_xcpt_gf_inst     (_frontend_io_cpu_resp_bits_xcpt_gf_inst),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_resp_bits_xcpt_ae_inst     (_frontend_io_cpu_resp_bits_xcpt_ae_inst),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_resp_bits_replay           (_frontend_io_cpu_resp_bits_replay),	// @[generators/rocket-chip/src/main/scala/rocket/Frontend.scala:386:28]
    .io_imem_btb_update_valid           (_core_io_imem_btb_update_valid),
    .io_imem_bht_update_valid           (_core_io_imem_bht_update_valid),
    .io_imem_flush_icache               (_core_io_imem_flush_icache),
    .io_dmem_req_ready                  (_dcacheArb_io_requestor_0_req_ready),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_req_valid                  (_core_io_dmem_req_valid),
    .io_dmem_req_bits_addr              (_core_io_dmem_req_bits_addr),
    .io_dmem_req_bits_tag               (_core_io_dmem_req_bits_tag),
    .io_dmem_req_bits_cmd               (_core_io_dmem_req_bits_cmd),
    .io_dmem_req_bits_size              (_core_io_dmem_req_bits_size),
    .io_dmem_req_bits_signed            (_core_io_dmem_req_bits_signed),
    .io_dmem_req_bits_dv                (_core_io_dmem_req_bits_dv),
    .io_dmem_s1_kill                    (_core_io_dmem_s1_kill),
    .io_dmem_s1_data_data               (_core_io_dmem_s1_data_data),
    .io_dmem_s2_nack                    (_dcacheArb_io_requestor_0_s2_nack),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_resp_valid                 (_dcacheArb_io_requestor_0_resp_valid),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_resp_bits_tag              (_dcacheArb_io_requestor_0_resp_bits_tag),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_resp_bits_data             (_dcacheArb_io_requestor_0_resp_bits_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_resp_bits_replay           (_dcacheArb_io_requestor_0_resp_bits_replay),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_resp_bits_has_data         (_dcacheArb_io_requestor_0_resp_bits_has_data),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_resp_bits_data_word_bypass (_dcacheArb_io_requestor_0_resp_bits_data_word_bypass),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_replay_next                (_dcacheArb_io_requestor_0_replay_next),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_s2_xcpt_ma_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ma_ld),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_s2_xcpt_ma_st              (_dcacheArb_io_requestor_0_s2_xcpt_ma_st),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_s2_xcpt_pf_ld              (_dcacheArb_io_requestor_0_s2_xcpt_pf_ld),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_s2_xcpt_pf_st              (_dcacheArb_io_requestor_0_s2_xcpt_pf_st),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_s2_xcpt_ae_ld              (_dcacheArb_io_requestor_0_s2_xcpt_ae_ld),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_s2_xcpt_ae_st              (_dcacheArb_io_requestor_0_s2_xcpt_ae_st),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_ordered                    (_dcacheArb_io_requestor_0_ordered),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_perf_release               (_dcacheArb_io_requestor_0_perf_release),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_dmem_perf_grant                 (_dcacheArb_io_requestor_0_perf_grant),	// @[generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:286:25]
    .io_ptw_status_debug                (_core_io_ptw_status_debug),
    .io_ptw_customCSRs_csrs_0_value     (_core_io_ptw_customCSRs_csrs_0_value),
    .io_wfi                             (_core_io_wfi)
  );
  assign auto_wfi_out_0 = wfiNodeOut_0_REG;	// @[generators/rocket-chip/src/main/scala/tile/Interrupts.scala:126:36]
endmodule

