// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLGPIO(
  input         clock,
                reset,
  output        auto_int_xing_out_sync_0,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_1,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_2,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_3,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_4,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_5,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_6,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_int_xing_out_sync_7,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_control_xing_in_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_control_xing_in_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [2:0]  auto_control_xing_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_control_xing_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [1:0]  auto_control_xing_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [15:0] auto_control_xing_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [28:0] auto_control_xing_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [3:0]  auto_control_xing_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input  [31:0] auto_control_xing_in_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_control_xing_in_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_control_xing_in_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_control_xing_in_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [2:0]  auto_control_xing_in_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [1:0]  auto_control_xing_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [15:0] auto_control_xing_in_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output [31:0] auto_control_xing_in_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_0_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_0_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_0_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_0_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_0_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_0_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_1_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_1_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_1_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_1_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_1_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_1_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_2_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_2_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_2_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_2_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_2_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_2_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_3_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_3_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_3_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_3_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_3_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_3_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_4_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_4_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_4_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_4_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_4_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_4_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_5_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_5_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_5_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_5_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_5_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_5_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_6_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_6_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_6_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_6_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_6_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_6_o_ds,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  input         auto_io_out_pins_7_i_ival,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
  output        auto_io_out_pins_7_o_oval,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_7_o_oe,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_7_o_ie,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_7_o_pue,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
                auto_io_out_pins_7_o_ds	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:366:18]
);

  wire             _out_wofireMux_T_2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire             out_backSel_4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire             out_backSel_2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire             out_backSel_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  wire [7:0]       _inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  wire [7:0]       _ieReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22]
  wire [7:0]       _pueReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22]
  wire [7:0]       _oeReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22]
  reg  [7:0]       portReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24]
  reg  [7:0]       dsReg_0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23]
  reg  [7:0]       valueReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27]
  reg  [7:0]       highIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26]
  reg  [7:0]       lowIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:91:26]
  reg  [7:0]       riseIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:92:26]
  reg  [7:0]       fallIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:93:26]
  reg  [7:0]       highIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:94:26]
  reg  [7:0]       lowIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:95:26]
  reg  [7:0]       riseIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:96:26]
  reg  [7:0]       fallIpReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:97:26]
  reg  [7:0]       passthruHighIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34]
  reg  [7:0]       passthruLowIeReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:99:34]
  reg  [7:0]       xorReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:106:26]
  wire             out_front_bits_read = auto_control_xing_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:69:36]
  wire             _out_out_bits_data_WIRE_20 = auto_control_xing_in_a_bits_address[11:7] == 5'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:70:19, :82:24]
  assign out_backSel_1 = auto_control_xing_in_a_bits_address[6:2] == 5'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_2 = auto_control_xing_in_a_bits_address[6:2] == 5'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_4 = auto_control_xing_in_a_bits_address[6:2] == 5'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign _out_wofireMux_T_2 = auto_control_xing_in_a_valid & auto_control_xing_in_d_ready & ~out_front_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:69:36, :82:24]
  wire [31:0]      _GEN = {{1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}, {_out_out_bits_data_WIRE_20}};	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:47:20, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire [31:0][7:0] _GEN_0 = {{8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {8'h0}, {passthruLowIeReg}, {passthruHighIeReg}, {xorReg}, {8'h0}, {8'h0}, {lowIpReg}, {lowIeReg}, {highIpReg}, {highIeReg}, {fallIpReg}, {fallIeReg}, {riseIpReg}, {riseIeReg}, {dsReg_0}, {_pueReg_io_q}, {portReg}, {_oeReg_io_q}, {_ieReg_io_q}, {valueReg}};	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :76:22, :77:22, :78:23, :79:22, :87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :106:26, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire [2:0]       controlXingIn_d_bits_opcode = {2'h0, out_front_bits_read};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:69:36, :100:19]
  always @(posedge clock) begin
    if (reset) begin
      portReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24]
      dsReg_0 <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :78:23]
      valueReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :87:27]
      highIeReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :90:26]
      lowIeReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :91:26]
      riseIeReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :92:26]
      fallIeReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :93:26]
      highIpReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :94:26]
      lowIpReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :95:26]
      riseIpReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :96:26]
      fallIpReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :97:26]
      passthruHighIeReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :98:34]
      passthruLowIeReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :99:34]
      xorReg <= 8'h0;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26]
    end
    else begin
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h3 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        portReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h5 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        dsReg_0 <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      valueReg <= _inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'hA & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        highIeReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'hC & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        lowIeReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:91:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h6 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        riseIeReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:92:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h8 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        fallIeReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:93:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      highIpReg <= ~(~highIpReg | (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'hB & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0] ? auto_control_xing_in_a_bits_data[7:0] : 8'h0)) | valueReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :87:27, :94:26, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      lowIpReg <= ~(~lowIpReg | (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'hD & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0] ? auto_control_xing_in_a_bits_data[7:0] : 8'h0)) | ~valueReg;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :87:27, :95:26, :112:14, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
      riseIpReg <= ~(~riseIpReg | (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h7 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0] ? auto_control_xing_in_a_bits_data[7:0] : 8'h0)) | ~valueReg & _inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :87:27, :96:26, :112:{14,24}, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23, src/main/scala/chisel3/util/OneHot.scala:58:35]
      fallIpReg <= ~(~fallIpReg | (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h9 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0] ? auto_control_xing_in_a_bits_data[7:0] : 8'h0)) | valueReg & ~_inSyncReg_inSyncReg_io_q;	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :87:27, :97:26, :113:{23,25}, generators/rocket-chip/src/main/scala/regmapper/RegField.scala:128:{60,63,69,74,95}, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23, src/main/scala/chisel3/util/OneHot.scala:58:35]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h11 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        passthruHighIeReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h12 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        passthruLowIeReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:99:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:2] == 5'h10 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
        xorReg <= auto_control_xing_in_a_bits_data[7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:106:26, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        portReg = _RANDOM[2'h0][7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24]
        dsReg_0 = _RANDOM[2'h0][15:8];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :78:23]
        valueReg = _RANDOM[2'h0][31:24];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :87:27]
        highIeReg = _RANDOM[2'h1][7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26]
        lowIeReg = _RANDOM[2'h1][15:8];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26, :91:26]
        riseIeReg = _RANDOM[2'h1][23:16];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26, :92:26]
        fallIeReg = _RANDOM[2'h1][31:24];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:90:26, :93:26]
        highIpReg = _RANDOM[2'h2][7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:94:26]
        lowIpReg = _RANDOM[2'h2][15:8];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:94:26, :95:26]
        riseIpReg = _RANDOM[2'h2][23:16];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:94:26, :96:26]
        fallIpReg = _RANDOM[2'h2][31:24];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:94:26, :97:26]
        passthruHighIeReg = _RANDOM[2'h3][7:0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34]
        passthruLowIeReg = _RANDOM[2'h3][15:8];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34, :99:34]
        xorReg = _RANDOM[2'h3][31:24];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:98:34, :106:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  IntSyncCrossingSource_7 intsource (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:28:31]
    .clock           (clock),
    .reset           (reset),
    .auto_in_0       (riseIpReg[0] & riseIeReg[0] | fallIpReg[0] & fallIeReg[0] | highIpReg[0] & highIeReg[0] | lowIpReg[0] & lowIeReg[0] | valueReg[0] & passthruHighIeReg[0] | ~(valueReg[0]) & passthruLowIeReg[0]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_1       (riseIpReg[1] & riseIeReg[1] | fallIpReg[1] & fallIeReg[1] | highIpReg[1] & highIeReg[1] | lowIpReg[1] & lowIeReg[1] | valueReg[1] & passthruHighIeReg[1] | ~(valueReg[1]) & passthruLowIeReg[1]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_2       (riseIpReg[2] & riseIeReg[2] | fallIpReg[2] & fallIeReg[2] | highIpReg[2] & highIeReg[2] | lowIpReg[2] & lowIeReg[2] | valueReg[2] & passthruHighIeReg[2] | ~(valueReg[2]) & passthruLowIeReg[2]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_3       (riseIpReg[3] & riseIeReg[3] | fallIpReg[3] & fallIeReg[3] | highIpReg[3] & highIeReg[3] | lowIpReg[3] & lowIeReg[3] | valueReg[3] & passthruHighIeReg[3] | ~(valueReg[3]) & passthruLowIeReg[3]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_4       (riseIpReg[4] & riseIeReg[4] | fallIpReg[4] & fallIeReg[4] | highIpReg[4] & highIeReg[4] | lowIpReg[4] & lowIeReg[4] | valueReg[4] & passthruHighIeReg[4] | ~(valueReg[4]) & passthruLowIeReg[4]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_5       (riseIpReg[5] & riseIeReg[5] | fallIpReg[5] & fallIeReg[5] | highIpReg[5] & highIeReg[5] | lowIpReg[5] & lowIeReg[5] | valueReg[5] & passthruHighIeReg[5] | ~(valueReg[5]) & passthruLowIeReg[5]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_6       (riseIpReg[6] & riseIeReg[6] | fallIpReg[6] & fallIeReg[6] | highIpReg[6] & highIeReg[6] | lowIpReg[6] & lowIeReg[6] | valueReg[6] & passthruHighIeReg[6] | ~(valueReg[6]) & passthruLowIeReg[6]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_in_7       (riseIpReg[7] & riseIeReg[7] | fallIpReg[7] & fallIeReg[7] | highIpReg[7] & highIeReg[7] | lowIpReg[7] & lowIeReg[7] | valueReg[7] & passthruHighIeReg[7] | ~(valueReg[7]) & passthruLowIeReg[7]),	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:87:27, :90:26, :91:26, :92:26, :93:26, :94:26, :95:26, :96:26, :97:26, :98:34, :99:34, :234:{34,40,51}, :235:{36,42,53}, :236:{36,42,53}, :237:{35,41,51}, :238:{35,41,60,67}, :239:{27,42,60}]
    .auto_out_sync_0 (auto_int_xing_out_sync_0),
    .auto_out_sync_1 (auto_int_xing_out_sync_1),
    .auto_out_sync_2 (auto_int_xing_out_sync_2),
    .auto_out_sync_3 (auto_int_xing_out_sync_3),
    .auto_out_sync_4 (auto_int_xing_out_sync_4),
    .auto_out_sync_5 (auto_int_xing_out_sync_5),
    .auto_out_sync_6 (auto_int_xing_out_sync_6),
    .auto_out_sync_7 (auto_int_xing_out_sync_7)
  );
  TLMonitor_56 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:24:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (auto_control_xing_in_d_ready),
    .io_in_a_valid        (auto_control_xing_in_a_valid),
    .io_in_a_bits_opcode  (auto_control_xing_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_control_xing_in_a_bits_param),
    .io_in_a_bits_size    (auto_control_xing_in_a_bits_size),
    .io_in_a_bits_source  (auto_control_xing_in_a_bits_source),
    .io_in_a_bits_address (auto_control_xing_in_a_bits_address),
    .io_in_a_bits_mask    (auto_control_xing_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_control_xing_in_a_bits_corrupt),
    .io_in_d_ready        (auto_control_xing_in_d_ready),
    .io_in_d_valid        (auto_control_xing_in_a_valid),
    .io_in_d_bits_opcode  (controlXingIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:100:19]
    .io_in_d_bits_size    (auto_control_xing_in_a_bits_size),
    .io_in_d_bits_source  (auto_control_xing_in_a_bits_source)
  );
  AsyncResetRegVec_w8_i0 oeReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[7:0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    .io_q  (_oeReg_io_q),
    .io_en (_out_wofireMux_T_2 & out_backSel_2 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  );
  AsyncResetRegVec_w8_i0 pueReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[7:0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    .io_q  (_pueReg_io_q),
    .io_en (_out_wofireMux_T_2 & out_backSel_4 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  );
  AsyncResetRegVec_w8_i0 ieReg (	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[7:0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
    .io_q  (_ieReg_io_q),
    .io_en (_out_wofireMux_T_2 & out_backSel_1 & _out_out_bits_data_WIRE_20 & auto_control_xing_in_a_bits_mask[0])	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24]
  );
  SynchronizerShiftReg_w8_d3 inSyncReg_inSyncReg (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  ({auto_io_out_pins_7_i_ival, auto_io_out_pins_6_i_ival, auto_io_out_pins_5_i_ival, auto_io_out_pins_4_i_ival, auto_io_out_pins_3_i_ival, auto_io_out_pins_2_i_ival, auto_io_out_pins_1_i_ival, auto_io_out_pins_0_i_ival}),	// @[generators/rocket-chip/src/main/scala/util/package.scala:37:27]
    .io_q  (_inSyncReg_inSyncReg_io_q)
  );
  assign auto_control_xing_in_a_ready = auto_control_xing_in_d_ready;
  assign auto_control_xing_in_d_valid = auto_control_xing_in_a_valid;
  assign auto_control_xing_in_d_bits_opcode = controlXingIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:100:19]
  assign auto_control_xing_in_d_bits_size = auto_control_xing_in_a_bits_size;
  assign auto_control_xing_in_d_bits_source = auto_control_xing_in_a_bits_source;
  assign auto_control_xing_in_d_bits_data = {24'h0, _GEN[auto_control_xing_in_a_bits_address[6:2]] ? _GEN_0[auto_control_xing_in_a_bits_address[6:2]] : 8'h0};	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:82:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  assign auto_io_out_pins_0_o_oval = portReg[0] ^ xorReg[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_0_o_oe = _oeReg_io_q[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_0_o_ie = _ieReg_io_q[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_0_o_pue = _pueReg_io_q[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_0_o_ds = dsReg_0[0];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_1_o_oval = portReg[1] ^ xorReg[1];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_1_o_oe = _oeReg_io_q[1];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_1_o_ie = _ieReg_io_q[1];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_1_o_pue = _pueReg_io_q[1];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_1_o_ds = dsReg_0[1];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_2_o_oval = portReg[2] ^ xorReg[2];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_2_o_oe = _oeReg_io_q[2];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_2_o_ie = _ieReg_io_q[2];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_2_o_pue = _pueReg_io_q[2];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_2_o_ds = dsReg_0[2];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_3_o_oval = portReg[3] ^ xorReg[3];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_3_o_oe = _oeReg_io_q[3];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_3_o_ie = _ieReg_io_q[3];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_3_o_pue = _pueReg_io_q[3];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_3_o_ds = dsReg_0[3];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_4_o_oval = portReg[4] ^ xorReg[4];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_4_o_oe = _oeReg_io_q[4];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_4_o_ie = _ieReg_io_q[4];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_4_o_pue = _pueReg_io_q[4];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_4_o_ds = dsReg_0[4];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_5_o_oval = portReg[5] ^ xorReg[5];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_5_o_oe = _oeReg_io_q[5];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_5_o_ie = _ieReg_io_q[5];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_5_o_pue = _pueReg_io_q[5];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_5_o_ds = dsReg_0[5];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_6_o_oval = portReg[6] ^ xorReg[6];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_6_o_oe = _oeReg_io_q[6];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_6_o_ie = _ieReg_io_q[6];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_6_o_pue = _pueReg_io_q[6];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_6_o_ds = dsReg_0[6];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
  assign auto_io_out_pins_7_o_oval = portReg[7] ^ xorReg[7];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:74:24, :106:26, :195:37, :231:{43,51}]
  assign auto_io_out_pins_7_o_oe = _oeReg_io_q[7];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:76:22, :196:40]
  assign auto_io_out_pins_7_o_ie = _ieReg_io_q[7];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:79:22, :198:40]
  assign auto_io_out_pins_7_o_pue = _pueReg_io_q[7];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:77:22, :194:41]
  assign auto_io_out_pins_7_o_ds = dsReg_0[7];	// @[generators/rocket-chip-blocks/src/main/scala/devices/gpio/GPIO.scala:78:23, :197:38]
endmodule

